Record = Record.java
Table = Table.java Record.java
Database = Database.java Table.java Record.java
Dabble = Dabble.java Database.java Table.java Record.java

%: %.java
	javac $@.java
	java -ea $@
